### ISSUE TITLE
Support nodeos 1.8 send_transaction

### ISSUE THREAD

**Issue by brandonfancher** [EOSIO/eosio-swift#137]
nodeos 1.8 adds `/v1/send_transaction` to replace the legacy `/v1/push_transaction`.

`push_transaction` reproduces the legacy trace format; this increases the load on nodeos.

`send_transaction` produces the new trace format.
 
See Issue 539 in the eosjs repo.

**Comment by brandonfancher** [comment]
See: https://github.com/EOSIO/eosjs/pull/545
See: https://github.com/EOSIO/eosjs/issues/539

**Comment by mjohnson12** [comment]
Resolved in https://github.com/EOSIO/eosio-swift/pull/232.
