### ISSUE TITLE
Support for Swift 5 and remove deprecation warnings.

### ISSUE THREAD

**Issue by ismyhc** [EOSIO/eosio-swift#194]
Right now, Swift 5 can be used, but at the cost of having to "convert to Swift 5" any time I run pod update, etc.

Also, after converting to Swift 5 there are a number of deprecation warnings.

These are produced by BigInt library and EosioSwift library.

**Comment by brandonfancher** [comment]
Thanks, @ismyhc. We have the Swift 5 upgrade on our radar for sure. In the short term, we will see about cleaning up some of those warnings that appear post-Swift-5 conversion.

**Comment by ismyhc** [comment]
@brandonfancher Looking forward to this as I plan on digging into soon. :)

**Comment by mjohnson12** [comment]
Swift 5 support has been merged into develop: https://github.com/EOSIO/eosio-swift/pull/228.
