### ISSUE TITLE
when support objective-C?

### ISSUE THREAD

**Issue by Dying5566** [EOSIO/eosio-swift#196]

**Comment by brandonfancher** [comment]
Hi @Dying5566. Swift and Objective-C are entirely interoperable. No further action is necessary to be able to use this library  with Objective-C.

**Comment by Switch26** [comment]
Here is a guide from Apple how to combine both Swift & Objective C in the same project:
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c
