### ISSUE TITLE
Improve Error message on Transaction Class

### ISSUE THREAD

**Issue by mauhcs** [EOSIO/eosio-swift#212]
The Transaction object keeps returning errors with the reason `self does not exist`
It is very hard to debug given this error message.

Could we have better description on the errors?

**Comment by brandonfancher** [comment]
Hi Mau. Thanks for your request. Logging this as an `enhancement` so that we can look into improving these error messages.

**Comment by mauhcs** [comment]
I understood what was causing this error. 
The reason was because the Transaction object was out of the scope when the event loop would call the `sign` function, hence the `self does not exist`.

I think this error message should be changed to `self does not exist. object left scope. Consider instantiating object outside the current scope.`

But I agree that now that I understand the problem and the data flow of the library, this is a very minor improvement and the current error message is OK. It helps if you know what you are doing as a concise remainder , but it is not friendly towards new users.

**Comment by brandonfancher** [comment]
Closing; we will work to improve error messages. But this appears to be related to the application's code, not the SDK's code.

**Comment by quochuynh67** [comment]
Hi @brandonfancher I stuck with this bug, I follow the example but the error `self does not exist` happen. How Can i fix it

Thanks you so much!

**Comment by brandonfancher** [comment]
Hi @quochuynh67. Do you have any example code you can post here? Could it be that your Transaction object is also leaving scope?
