### ISSUE TITLE
Apple Compliance Question about Standard Encryption

### ISSUE THREAD

**Issue by mauhcs** [EOSIO/eosio-swift#214]
Submitting my App using EosioSwift I got this standard compliance question. 
I think the answer should be yes, or the Elliptical cryptography is provided by a standard library by apple? 

Is it possible to streamline this question with some entry in the plist file?
If so, I would like to suggest a "how to" in the readMe.

![Screen Shot 2019-09-05 at 0 09 16](https://user-images.githubusercontent.com/17294645/64267518-83bd8300-cf71-11e9-97fa-02538c307243.png)

**Comment by brandonfancher** [comment]
We cannot tell you how you are supposed to answer this question for your application. This is dependent on your application.
