### ISSUE TITLE
Error details lost in transaction signing and other flows.

### ISSUE THREAD

**Issue by opi-smccoole** [EOSIO/eosio-swift#227]
In `signWithBioCheck` and in other locations the SDK may create an EosioError with an `EosioErrorCode` of `.unexpectedError` from a base Error or NSError.  This is at EosioError around line 191 where there is an extension on Error called `eosioError`.  However, then the `reason` member is set with the error localized description and all other information about the original error is then lost.  This makes it very difficult for calling code to respond in an appropriate way and makes identification of the error dependent on a localized string, which is not practical.  EosioError contains an `originalError` member that should be set to the error that is being used to initialize the instance.  `originalError` is currently NSError so the error will have to be cast.  Longer term it would possibly be better to migrate originalError's type to Error and provide an extension on Error for easy casting to NSError, although with toll free bridging, this is not particularly difficult.

**Comment by mjohnson12** [comment]
Resolved with https://github.com/EOSIO/eosio-swift/pull/230.
