### ISSUE TITLE
Unable to serialize Action data 

### ISSUE THREAD

**Issue by shamtroon** [EOSIO/eosio-swift#242]
Hello guys,
I am working on **eosio.msig**  and I am tired to serialize my action data. I also worked on Android app using eosio-java and it is working fine. But in swift I didn't get any success. Kindly help me.

**Comment by brandonfancher** [comment]
@shamtroon Can you provide more information? Maybe some code examples of how you are trying to do the serialization?

**Comment by shamtroon** [comment]
Yes, here is my code : 

```
transaction.add(action: action)
print("Action Data = \(action.data)")
print(action.account)

transaction.prepare(completion: { (error) in
print(error)
})

let serializeData = try transaction.serializeTransaction()
```

If I sign and broadcast my transaction. I didn't get any error, but when I serialize my Action data then it shows error  **self does not exist**

**Comment by brandonfancher** [comment]
Thanks, @shamtroon. Can you show us also the code where you instantiation the `EosioTransaction` and the `action`?

**Comment by opi-smccoole** [comment]
Please call: 
```
IndyAgreement(
Legalese: EosioName(from),
agreementDoc: "hey",
shareholders: shareholders).toJsonString().jsonToDictionary()
```
If there are any errors, then you will probably need to fix your data object so that it converts properly.

**Comment by shamtroon** [comment]
Thanks for your response, I solve my issue using following code: 

```
transaction.prepare { result in
   print("Prepare data = \(result)")

   switch result {
      case .failure (let error):
         DispatchQueue.main.async {

         }
         print("ERROR Prepare Transaction Sham")
         print(error) 
         print(error.reason)
   
      case .success:
         try! transaction.serializeActionData()
         print("transation = \(try! transaction.toJson(prettyPrinted: true))")

   }

}
```
