### ISSUE TITLE
How to get response object from signAndBroadcast?

### ISSUE THREAD

**Issue by ismyhc** [EOSIO/eosio-swift#248]
As illustrated below, when using the signAndBroadcast function, the result only return bool or error.

In my custom implementation, I used the response object to build a temporary transaction to display to the user. 

How can I get the response object when pushing a transaction?

```
    /// Signs a transaction and then broadcasts it.
    ///
    /// - Parameter completion: Called with an `EosioResult` consisting of a `Bool` for success and an optional `EosioError`.
    public func signAndBroadcast(completion: @escaping (EosioResult<Bool, EosioError>) -> Void) {
        sign { [weak self] (result) in
            guard let strongSelf = self else {
                return completion(.failure(EosioError(.unexpectedError, reason: "self does not exist")))
            }
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success:
                strongSelf.broadcast(completion: completion)
            }
        }
    }
```

**Comment by ismyhc** [comment]
Okay, so after digging in more, I think I understand how its meant to be used.

Im building my transaction object like so.

```
do {
    
    let data = try TransferData(from: EosioName(account.name), to: EosioName(receipient), quantity: quantity, memo: memo)
    let action = try EosioTransaction.Action(account: EosioName(tokenContract.contract), name: EosioName("transfer"),
                                             authorization: [EosioTransaction.Action.Authorization(actor: EosioName(account.name),
                                                                                                   permission: EosioName("active"))],
                                             data: data)
    
    let transaction = EosioTransaction()
    transaction.add(action: action)

    
    OperationManager.shared.add(TransactionOperation(chainProvider: chainProvider, transaction: transaction), queue: .backgroundSeq) { result in
        print(transaction.transactionId)
        completion?(result)
    }
    
} catch {
    completion?(.failure(OperationError.dataFailure("Error creating Transfer Action")))
}
```

Now, with that, I can see that the transaction object used to call the signAndBroadcast function on, gets updated with the response info, such as transactionId, etc once the response comes back successfully. 

Im assuming this is the expected way of obtaining the transaction response rather than using the raw response from the server.

I would like to suggest some examples or mention of this in the docs as it was not clear. Of course, maybe it is in the docs somewhere and I completely missed it :)

Feel free to close if Im on the right track.

**Comment by opi-smccoole** [comment]
Yes, you're on the right track as far as using signAndBroadcast.  It's supposed to be a convenience function to do all of the flow with minimal developer intervention.  If the full response is desired, then what you would do is to just call `sign` on the transaction, get the serialized form, create a send or push transaction request and submit it using `sendTransaction` or `pushTransaction` from the RPC provider.  Essentially your code would have to do what the `broadcast` method in Transaction does.
