### ISSUE TITLE
Is there any possibility to get the detailed error reason

### ISSUE THREAD

**Issue by jke661s** [EOSIO/eosio-swift#293]
Hello,

I was trying to do a transfer action but get the 500 error back including the reason saying "Invalid HTTP response (500) for https://jungle3.cryptolions.io:443/v1/chain/send_transaction."

I am just wondering whether there is a way to get the detailed error message? For example, "CPU/ NET/ Resource exhausted", "Not enough token balance", "Invalid account" etc.

Cheers.

**Comment by opi-smccoole** [comment]
Since it is a 500 error we are not going to try to decode any return from the server.  EosioError contains an `originalError` member that you can check for additional information.  If `originalError` is itself an EosioError, you can keep drilling downward until you reach the root error.

**Comment by jke661s** [comment]
Thanks @opi-smccoole I'll have a try.

**Comment by skygrid-engineering** [comment]
@opi-smccoole my "originalError" is not an EosioError, it's a PromiseKit.PMKHTTPError. I've been stepping through the promise kit code looking for any additional information. This is an EOSIO 2.0.5 instance. I'm using the getBlock workaround since getBlockInfo isn't supported. I feel like I'm close. The promise kit code is gnarly. Is there anything I can do to find out more information about that 500?

**Comment by opi-smccoole** [comment]
It seems like it might be something related to the transaction itself since its getting through all the other steps like fetching the abi and available keys.  Can you show the entirety of the request JSON for the send_transaction?

**Comment by skygrid-engineering** [comment]
@opi-smccoole sure thing and thanks for the quick response


```
Request JSON: {"available_keys":["PUB_K1_5bJXzSd2t5D4T1QJqT5sCtYE7j4Zkfri3cLMjKGjS524cvDyqR"],"transaction":{"actions":[{"account":"skygridhub","authorization":[{"actor":"hax4baotsm2b","permission":"active"}],"data":"7084c4999a43ba697084c4999a43ba690000000020178fae000000000000000000000000000000000000803f0000803f0000803f0000803f0000803f0000803f0000803f00000000000000000552454144590100000000000000010000000000000006737461747573000000000000000003736466","name":"heartbeat"}],"context_free_actions":[],"delay_sec":0,"expiration":"2021-03-24T04:55:22.000","max_cpu_usage_ms":0,"max_net_usage_words":0,"ref_block_num":57471,"ref_block_prefix":3287217651,"transaction_extensions":[]}}
EosioRpcProvider.decodeResponse: {
  "required_keys" : [
    "EOS5bJXzSd2t5D4T1QJqT5sCtYE7j4Zkfri3cLMjKGjS524ggU7Fy"
  ]
}


attempts required = 5
Request JSON: {"compression":0,"packed_context_free_data":"","packed_trx":"3ac65a607fe0f3f5eec3000000000100c0d12db9cb3cc40000c8469d7c8d6a017084c4999a43ba6900000000a8ed3232757084c4999a43ba697084c4999a43ba690000000020178fae000000000000000000000000000000000000803f0000803f0000803f0000803f0000803f0000803f0000803f0000000000000000055245414459010000000000000001000000000000000673746174757300000000000000000373646600","signatures":["SIG_K1_KAjcuhgYdvwfRbDzS4PwRLwp1DCi6YCVbTgudJ7nrX3GP1nxFzLxjgDL57Gmz9i7a3BxsWJkiEKLp3JgmtmzjzRZtQmQXm"]}
```

and for the GetBlockInfo workaround I'm using getInfo for the head block and then building the ref and prefix like pictured below

**Comment by skygrid-engineering** [comment]
@opi-smccoole Got it. Two things - I was able to determine it was a smart contract exception that we had put in so yes, it's user error on my part. But, shouldn't this SDK have been able to show me the error details? Here's what led me to this conclusion. I just rebuild the send_transaction request in postman where I could see the error details. 

That "invalid state value" would have told me everything I needed to know.

![image](https://user-images.githubusercontent.com/49753093/112340759-dca55700-8c8e-11eb-8a5d-0583bfc89827.png)

**Comment by opi-smccoole** [comment]
Glad that you got it going!  I understand what you mean.  Unfortunately the server must also be returning a true 500 HTTP Error code.  The code [here](https://github.com/EOSIO/eosio-swift/blob/master/Sources/EosioSwift/EosioRpcProvider/EosioRpcProvider.swift#L334) handles the DataTask and that means that we get pushed into the PromiseKit error flow right away, so there's no opportunity to try to parse the return message and we might encounter problems with parsing different error return formats.  Something to replace PromiseKit's [validate()](https://github.com/PromiseKit/Foundation/blob/1a276e598dac59489ed904887e0740fa75e571e0/Sources/NSURLSession%2BPromise.swift#L233) could possibly look at logging the response body but we don't currently have anyone to work on enhancements.  PR's would be welcome for consideration.
